Repository libxmp/libxmp, pull requests merged in 2022-02, with the labels that each got.

#561 Fix multiple IT playback bugs affecting Atomic Playboy.
  src/player.c
  src/player.h
  src/read_event.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/default_volume.it
  test-dev/data/default_volume_it.data
  test-dev/data/portamento_after_cut_fade.data
  test-dev/data/portamento_sustain.data
  test-dev/data/portamento_sustain.it
  test-dev/openmpt/it/00_README
  test-dev/openmpt/it/Fade-Porta.data
  test-dev/openmpt/it/Off-Porta-CompatGxx.data
  test-dev/openmpt/it/Off-Porta-CompatGxx.it
  test-dev/openmpt/it/Off-Porta.data
  test-dev/openmpt/it/Off-Porta.it
  test-dev/openmpt/it/porta-offset.data
  test-dev/openmpt/it/porta-offset.it
  test-dev/test_player_it_default_volume.c
  test-dev/test_player_it_portamento_sustain.c
Labels: bug, it

#565 Fix NNA and tone portamento interaction with sample changes.
  src/read_event.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/portamento_nna_sample.data
  test-dev/data/portamento_nna_sample.it
  test-dev/test_player_it_portamento_nna_sample.c
  test/test.c
Labels: bug, it

#539 Update the bzip2 depacker code to a newer 0BSD-licensed version
  src/depackers/bunzip2.c
  src/depackers/crc32.c
  src/depackers/crc32.h
Labels: depackers

#567 Fix IT duplicate note check to use the key prior to transpose.
  src/mixer.h
  src/read_event.c
  src/virtual.c
  src/virtual.h
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/duplicate_check_transpose.data
  test-dev/data/duplicate_check_transpose.it
  test-dev/test_player_it_duplicate_check_transpose.c
Labels: bug, it

#571 Fix for IT filter cutoff 127 on new note behavior.
  src/effects.c
  src/player.c
  src/player.h
  src/read_event.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/compare_mixer_data.c
  test-dev/data/it_channel_filter.data
  test-dev/data/it_channel_filter.it
  test-dev/openmpt/it/CarryNNA.data
  test-dev/openmpt/it/filter-reset-carry.data
  test-dev/openmpt/it/filter-reset.data
  test-dev/test_player_it_channel_filter.c
Labels: bug, it

#573 Add IT MIDI macro filter effects support.
  src/common.h
  src/effects.c
  src/effects.h
  src/load.c
  src/load_helpers.c
  src/loaders/it.h
  src/loaders/it_load.c
  src/player.c
  src/player.h
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_it_invalid_fx.data
  test-dev/data/it_smooth_macro.data
  test-dev/data/it_smooth_macro.it
  test-dev/openmpt/it/00_README
  test-dev/openmpt/it/MacroExtendedParam.data
  test-dev/openmpt/it/MacroExtendedParam.it
  test-dev/openmpt/it/MultiZxx.data
  test-dev/openmpt/it/MultiZxx.it
  test-dev/openmpt/it/Volume-Macro-Letters.data
  test-dev/openmpt/it/ZxxSecrets.data
  test-dev/openmpt/it/ZxxSecrets.it
  test-dev/openmpt/it/fltmacro.data
  test-dev/openmpt/it/macro-lastnote.data
  test-dev/test_effect_it_smooth_macro.c
  test-dev/test_openmpt_it_fltmacro.c
  test-dev/test_openmpt_it_macro_extended_param.c
  test-dev/test_openmpt_it_macro_lastnote.c
  test-dev/test_openmpt_it_multizxx.c
  test-dev/test_openmpt_it_volume_macro_letters.c
  test-dev/test_openmpt_it_zxxsecrets.c
Labels: enhancement, it
