Repository libxmp/libxmp, pull requests merged in 2024-12, with the labels that each got.

#785 Implement support for Protracker instrument swapping.
  src/mixer.c
  src/mixer.h
  src/read_event.c
  src/virtual.c
  src/virtual.h
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/compare_mixer_data.c
  test-dev/openmpt/mod/01_TODO
  test-dev/openmpt/mod/InstrSwapRetrigger.data
  test-dev/openmpt/mod/PTInstrSwap.data
  test-dev/openmpt/mod/PTInstrVolume.data
  test-dev/openmpt/mod/PTStoppedSwap.data
  test-dev/openmpt/mod/PTSwapEmpty.data
  test-dev/openmpt/mod/PTSwapNoLoop.data
  test-dev/openmpt/mod/PortaSmpChange_PT.data
  test-dev/openmpt/mod/PortaSwapPT.data
  test-dev/test.h
  test-dev/test_openmpt_mod_instrswapretrigger.c
  test-dev/test_openmpt_mod_portasmpchange.c
  test-dev/test_openmpt_mod_portaswappt.c
  test-dev/test_openmpt_mod_ptinstrswap.c
  test-dev/test_openmpt_mod_ptinstrvolume.c
  test-dev/test_openmpt_mod_ptstoppedswap.c
  test-dev/test_openmpt_mod_ptswapempty.c
  test-dev/test_openmpt_mod_ptswapnoloop.c
Labels: enhancement, mod

#790 Apply fix from #99 to the module scan too.
  src/effects.c
  src/scan.c
Labels: bug, it

#791 Fix loading of Poly Tracker (PTM) unused sample names.
  src/loaders/ptm_load.c
  test-dev/data/format_ptm.data
Labels: bug

#803 Fix defects found by libFuzzer, holiday edition.
  src/common.h
  src/lfo.c
  src/loaders/arch_load.c
  src/loaders/dbm_load.c
  src/loaders/dt_load.c
  src/loaders/it_load.c
  src/loaders/med4_load.c
  src/loaders/mgt_load.c
  src/loaders/rtm_load.c
  src/loaders/sample.c
  src/scan.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/f/load_arch_invalid_sample_loops
  test-dev/data/f/load_dbm_bad_fx_conv.data
  test-dev/data/f/load_dbm_bad_fx_conv.dbm
  test-dev/data/f/load_dt_duplicate_patt.dtm
  test-dev/data/f/load_dt_invalid_channel_count.dtm
  test-dev/data/f/load_dt_invalid_header_size.dtm
  test-dev/data/f/load_dt_invalid_instrument_count.dtm.xz
  test-dev/data/f/load_dt_invalid_loop.dtm
  test-dev/data/f/load_dt_invalid_sample_loop.dtm
  test-dev/data/f/load_med4_invalid_sample4.med
  test-dev/data/f/load_med4_invalid_sample5.med
  test-dev/data/f/load_mgt_invalid_track_offset.mgt
  test-dev/data/f/play_it_adpcm_bound.it
  test-dev/data/f/play_it_vol_clamp.data
  test-dev/data/f/play_it_vol_clamp.it
  test-dev/data/f/play_rtm_autovib_oob_depth_rate.data
  test-dev/data/f/play_rtm_autovib_oob_depth_rate.rtm
  test-dev/data/longest.med
  test-dev/test_fuzzer_arch_invalid.c
  test-dev/test_fuzzer_arch_invalid_patterns.c
  test-dev/test_fuzzer_dbm_bad_fx_conv.c
  test-dev/test_fuzzer_dbm_truncated.c
  test-dev/test_fuzzer_dbm_truncated_inst.c
  test-dev/test_fuzzer_dt_channels_bound.c
  test-dev/test_fuzzer_dt_duplicate_chunk.c
  test-dev/test_fuzzer_dt_instrument_count.c
  test-dev/test_fuzzer_dt_invalid.c
  test-dev/test_fuzzer_dt_invalid_loop.c
  test-dev/test_fuzzer_med4_invalid_sample.c
  test-dev/test_fuzzer_mgt_invalid.c
  test-dev/test_fuzzer_play_it_adpcm_bound.c
  test-dev/test_fuzzer_play_it_vol_clamp.c
  test-dev/test_fuzzer_play_rtm_autovib.c
  test-dev/test_player_scan.c
Labels: bug, it, med

#805 Do not apply FT2 bugs quirk to Modplug Tracker XMs.
  src/loaders/xm_load.c
  test-dev/test_api_seek_time.c
Labels: bug, xm

#809 Scan should only count one instance of pattern delay per row.
  src/scan.c
  test-dev/openmpt/xm/01_TODO
  test-dev/openmpt/xm/PatternDelays.data
Labels: bug, mod, xm

#811 cmake: quote libxmp.map path in LINK_FLAGS for paths with spaces
  CMakeLists.txt
  lite/CMakeLists.txt
Labels: buildsystem

#813 Fix various bugs in the Liquid Tracker loader.
  docs/Changelog
  docs/formats.txt
  src/loaders/liq_load.c
  src/loaders/no_load.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_liq.data
  test-dev/data/format_liq_100.data
  test-dev/data/format_liq_no_fx.data
  test-dev/data/m/liquid pain.liq
  test-dev/test_loader_liq_100.c
Labels: bug

#814 Stop reading Liquid Tracker instrument names out-of-bounds.
  src/loaders/liq_load.c
  test-dev/data/format_liq_100.data
Labels: bug

#817 Add XM extra fine portamento memory, unlink XM 1xx/2xx memory.
  docs/Changelog
  lite/Changelog
  src/effects.c
  src/effects.h
  src/player.h
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/openmpt/xm/01_TODO
  test-dev/openmpt/xm/Porta-LinkMem.data
  test-dev/test_openmpt_xm_porta_linkmem.c
Labels: bug, xm

#818 Reset Invert Loop position when a new instrument is encountered.
  docs/Changelog
  src/player.c
Labels: bug, mod

#819 Fix rare mixer crash when reversing a sample past its end.
  src/mixer.c
  test-dev/data/f/play_it_reverse_past_end.it
  test-dev/test_fuzzer_play_it_sustain_bidi.c
Labels: bug, it, xm, med

#820 Fix mixer uninitialized reads caused by truncated samples.
  src/loaders/sample.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/f/play_it_truncated_sample.it
  test-dev/test_fuzzer_it_truncated.c
  test-dev/test_fuzzer_it_truncated_header.c
  test-dev/test_fuzzer_it_truncated_pattern.c
  test-dev/test_fuzzer_play_it_truncated.c
Labels: bug, it, xm, s3m, med
