Repository libxmp/libxmp, pull requests merged in 2024-11, with the labels that each got.

#770 Add support for Ultra Tracker tempo commands.
  src/effects.c
  src/effects.h
  src/loaders/ult_load.c
  src/scan.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_ult.data
  test-dev/data/ult_effectF.data
  test-dev/data/ult_effectF.ult
  test-dev/test_effect_ult_tempo.c
Labels: bug

#773 Add HWAddressSanitizer fuzzer (AArch64 only).
  test-dev/Makefile.in
  test-dev/libxmp_fuzz.sh
Labels: enhancement

#772 Fix test_mixer_bidi_sync to test different interpolation modes.
  test-dev/test_mixer_bidi_sync.c
Labels: bug

#774 Merge song file instrument path detection routines.
  src/bitrot/loaders/ssmt_load.c
  src/loaders/common.c
  src/loaders/loader.h
  src/loaders/med2_load.c
  src/loaders/mod_load.c
  src/loaders/stm_load.c
Labels: enhancement

#777 Make the presence of invert loop override tracker ID guesses.
  src/loaders/mod_load.c
Labels: bug, mod

#779 Clean up jank in mixer.c sample loop handling.
  src/mixer.c
Labels: bug

#781 Fix crash when calling xmp_set_instrument_path with NULL.
  docs/libxmp.rst
  src/control.c
  src/loaders/common.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/test_api_set_instrument_path.c
Labels: bug

#788 build: don't use -W if -Wno-unused-parameter isn't supported
  cmake/libxmp-checks.cmake
  configure.ac
  lite/configure.ac
Labels: buildsystem
