Repository libxmp/libxmp, pull requests merged in 2025-05, with the labels that each got.

#843 Fix loading of Extreme Pinball modules
  src/loaders/masi_load.c
Labels: bug

#845 Fix bugs in position seek functions and clarify API seek edge cases.
  docs/Changelog
  docs/libxmp.rst
  src/common.h
  src/control.c
  src/player.c
  src/scan.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/libxmp_fuzz.c
  test-dev/test_api_next_position.c
  test-dev/test_api_prev_position.c
  test-dev/test_api_set_position.c
  test-dev/test_api_set_row.c
  test-dev/test_player_scan.c
Labels: bug, API

#848 Fix array subscript underflow in Pha Packer loader.
  docs/Changelog
  src/loaders/prowizard/pha.c
  test-dev/data/f/prowizard_pha_invalid_ocpt
  test-dev/data/f/prowizard_pha_invalid_ocpt2
  test-dev/test_fuzzer_prowizard_pha_invalid.c
Labels: bug

#852 Remove remaining loader pattern loop integer division usage.
  docs/Changelog
  src/loaders/okt_load.c
  src/loaders/sfx_load.c
Labels: enhancement

#851 Fix broken conversion of ProRunner 2.0 pattern data.
  docs/Changelog
  src/loaders/prowizard/prun2.c
  test-dev/data/format_pru2.data
Labels: bug

#853 xmp_set_tempo_factor no longer modifies frame time prior to rescan.
  docs/Changelog
  docs/libxmp.rst
  lite/Changelog
  src/common.h
  src/effects.c
  src/far_extras.c
  src/load_helpers.c
  src/player.c
  src/scan.c
  test-dev/test_api_set_tempo_factor.c
Labels: bug, API

#854 minor build system tweaks:
  CMakeLists.txt
  Makefile.in
  configure.ac
  lite/CMakeLists.txt
  lite/Makefile.in
  lite/configure.ac
Labels: buildsystem

#857 Add flow mode support for loop/jump/break interactions.
  docs/Changelog
  lite/Changelog
  src/common.h
  src/effects.c
  src/flow.c
  src/loaders/dt_load.c
  src/loaders/it_load.c
  src/loaders/mod_load.c
  src/loaders/ptm_load.c
  src/player.c
  src/player.h
  src/scan.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_ptm.data
  test-dev/data/pattern_loop_dt_breakjump.dtm
  test-dev/data/pattern_loop_dt_breakjump.mod
  test-dev/data/pattern_loop_dt_breakjump_dtm.data
  test-dev/data/pattern_loop_dt_breakjump_mod.data
  test-dev/data/pattern_loop_imf_breakjump.imf
  test-dev/data/pattern_loop_imf_breakjump.s3m
  test-dev/data/pattern_loop_imf_breakjump_imf.data
  test-dev/data/pattern_loop_imf_breakjump_s3m.data
  test-dev/data/pattern_loop_it100_breakjump.data
  test-dev/data/pattern_loop_it100_breakjump.it
  test-dev/data/pattern_loop_it200_breakjump.data
  test-dev/data/pattern_loop_it200_breakjump.it
  test-dev/data/pattern_loop_liq_breakjump.data
  test-dev/data/pattern_loop_liq_breakjump.liq
  test-dev/data/pattern_loop_liq_breakjump_no.data
  test-dev/data/pattern_loop_liq_breakjump_no.liq
  test-dev/data/pattern_loop_mpt_breakjump.it
  test-dev/data/pattern_loop_mpt_breakjump.s3m
  test-dev/data/pattern_loop_mpt_breakjump.xm
  test-dev/data/pattern_loop_mpt_breakjump_it.data
  test-dev/data/pattern_loop_mpt_breakjump_s3m.data
  test-dev/data/pattern_loop_mpt_breakjump_xm.data
  test-dev/data/pattern_loop_octalyser_breakjump.data
  test-dev/data/pattern_loop_octalyser_breakjump.mod
  test-dev/data/pattern_loop_ptm_breakjump.data
  test-dev/data/pattern_loop_ptm_breakjump.ptm
  test-dev/data/pattern_loop_st301_breakjump.data
  test-dev/data/pattern_loop_st301_breakjump.s3m
  test-dev/data/pattern_loop_st321_breakjump.data
  test-dev/data/pattern_loop_st321_breakjump.s3m
  test-dev/test_effect_pattern_loop_dt_breakjump.c
  test-dev/test_effect_pattern_loop_dt_breakjump_mod.c
  test-dev/test_effect_pattern_loop_imf_breakjump.c
  test-dev/test_effect_pattern_loop_imf_breakjump_s3m.c
  test-dev/test_effect_pattern_loop_it100_breakjump.c
  test-dev/test_effect_pattern_loop_it200_breakjump.c
  test-dev/test_effect_pattern_loop_liq_breakjump.c
  test-dev/test_effect_pattern_loop_liq_breakjump_no.c
  test-dev/test_effect_pattern_loop_mpt_breakjump_it.c
  test-dev/test_effect_pattern_loop_mpt_breakjump_s3m.c
  test-dev/test_effect_pattern_loop_mpt_breakjump_xm.c
  test-dev/test_effect_pattern_loop_octalyser_breakjump.c
  test-dev/test_effect_pattern_loop_ptm_breakjump.c
  test-dev/test_effect_pattern_loop_st301_breakjump.c
  test-dev/test_effect_pattern_loop_st321_breakjump.c
Labels: bug, mod, it, xm, s3m

#860 Fix loading XMs with harmless pattern truncation on event bounds.
  docs/Changelog
  lite/Changelog
  src/loaders/xm_load.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_xm_pattrunc.data
  test-dev/data/format_xm_pattrunc.xm
  test-dev/test_loader_xm_pattrunc.c
Labels: bug, xm

#861 Fix Digital Tracker instrument finetune field.
  docs/Changelog
  src/loaders/dt_load.c
Labels: bug, dtm

#862 Add Software Visions DMF support to the MOD loader.
  docs/Changelog
  docs/formats.txt
  src/loaders/mod_load.c
  test-dev/Makefile.in
  test-dev/all_tests.txt
  test-dev/data/format_mod_svdmf.data
  test-dev/data/m/FROZEN.DMF
  test-dev/test_loader_mod_svdmf.c
Labels: mod, new format

#868 Add the formula for resonance_table to filter.c
  src/filter.c
Labels: it
